site_name: MDIBL Comparative Genomics and Data Science Core
nav:
  - Home: index.md
  - About:
    - Team: home/team.md
    - Contact: home/contact.md
  - Bioinformatics Bits: 
    - bits/index.md
    - Bit 1: bits/bit1.md
    - Bit 2: bits/bit2.md
  - Introduction to Workflows in the Cloud Course:
    - introToCloudCourse/index.md
    - Instructors: introToCloudCourse/instructors.md
    - Learning Resources: introToCloudCourse/learningResources.md
    - Arrival: introToCloudCourse/arrival.md
    - Sequin: introToCloudCourse/sequin.md
  - Course Archives:
    - courseArchives/index.md
    - ScRNAseq in the Cloud:
      - courseArchives/scrnaseq2024/index.md 
      - Insctructors: courseArchives/scrnaseq2024/instructors.md
      - Learning Resources: courseArchives/scrnaseq2024/learning_resources.md
      - Arrival: courseArchives/scrnaseq2024/arrival.md
      - Launch: courseArchives/scrnaseq2024/launch.md
      - Debug: courseArchives/scrnaseq2024/debug.md
      - Output: courseArchives/scrnaseq2024/output.md
      - Loupe Browser: courseArchives/scrnaseq2024/loupe.md
    - Introduction to Workflows in the Cloud: 
      - courseArchives/introCloud2024/index.md
      - Instructors: courseArchives/introCloud2024/instructors.md
      - Learning Resources: courseArchives/introCloud2024/learningResources.md
      - Arrival: courseArchives/introCloud2024/arrival.md
      - Sequin: courseArchives/introCloud2024/sequin.md
theme:
  name: material
  icon:
    logo: simple/mediapipe       
  features: 
    - navigation.indexes
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.footer
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle: 
        icon: material/toggle-switch-off-outline
        name: Switch to Dark Mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle: 
        icon: material/toggle-switch
        name: Switch to Light Mode
      primary: custom
      accent: custom
repo_url: https://github.com/mdibl/mdibl.github.io
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg